// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIHHhOzx7Bl1Okl2WiIvKV9DOjW_JLe7c',
    appId: '1:1040815805785:web:e533033bfa4697fc1ee848',
    messagingSenderId: '1040815805785',
    projectId: 'flutter-project-e37bb',
    authDomain: 'flutter-project-e37bb.firebaseapp.com',
    storageBucket: 'flutter-project-e37bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEkzD8Z9_aGcR1mZVJHnjjIIRbyEaEHb8',
    appId: '1:1040815805785:android:b2a4d8f235df28b51ee848',
    messagingSenderId: '1040815805785',
    projectId: 'flutter-project-e37bb',
    storageBucket: 'flutter-project-e37bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgSo1t-qx2-DuMYZUFCa_b9jL29Bv8nhk',
    appId: '1:1040815805785:ios:831e5b72a4eb4d401ee848',
    messagingSenderId: '1040815805785',
    projectId: 'flutter-project-e37bb',
    storageBucket: 'flutter-project-e37bb.appspot.com',
    iosClientId: '1040815805785-ldltkrf7f8oqup91v48r2p7gm07341m7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgSo1t-qx2-DuMYZUFCa_b9jL29Bv8nhk',
    appId: '1:1040815805785:ios:3bf09731a7d671dd1ee848',
    messagingSenderId: '1040815805785',
    projectId: 'flutter-project-e37bb',
    storageBucket: 'flutter-project-e37bb.appspot.com',
    iosClientId: '1040815805785-ht72afo8lm134o4ggcjbcm7bvcj5d4lj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject2.RunnerTests',
  );
}
